### ISSUE TITLE
There shouldn't be an 'automate' button

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#119]
The automation manager view shouldn't have a button that called the `automate()` function. Instead, that function should be being called every time a view is changed to create the illusion that the tasks are being handled automatically.

If I get the chance, I'll fix this myself, but I figured I'd make the bug report now.

**Comment by kofi12** [comment]
Alright, can you delete the button in `AutomationView` alongside the fix, should be around line 45 ish

**Comment by kofi12** [comment]
closed by accident lol

**Comment by glassyeyedfish** [comment]
Looks like the button's gone. Closing this.
