### ISSUE TITLE
Make a system to deal with invalid inputs to text fields

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#14]

**Comment by glassyeyedfish** [comment]
I've added a system in the `iter1-input-validation` branch that basically just uses a string to hold an error message, and if that string is empty then there are no errors and so the product is added to the database.

**Comment by kofi12** [comment]
I've tested this fix and it works well as far as I can tell

**Comment by glassyeyedfish** [comment]
Cool, I'll be closing this then.
