### ISSUE TITLE
Exception occurs sometimes when you remove an item.

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#15]
This code in "DatabaseStub" is responsible.

@Override
public void removeProduct(Integer barcode) {
    for(Product p: dbStub){
        if(p.getBarcode().intValue() == barcode.intValue()){
            dbStub.remove(p);
        }
    }
}

**Comment by kofi12** [comment]
Remove now works smoothly.
