### ISSUE TITLE
DOC: Class Diagrams w/ Justifications

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#20]

**Comment by kofi12** [comment]
@glassyeyedfish @LJWoolner Just need your design justifications for Database and Logic then I can close this issue along with the wiki. Thanks

**Comment by glassyeyedfish** [comment]
Alright, here's my blurb:

The business logic is split into an interface `ILogic` and an implementation `Logic`. Later we might split up the functionality, but for now it's not needed. The `ILogic` interface can be used by the `Display` package as a go-between to interact with the database. If there is an action that the user can take, there should be a corresponding function in the `ILogic` interface.

The `Logic` class implements these functions. The `Logic` class is also responsible for assigning barcodes to new products that are added to the database. That is why it stores the value of the `nextBarcode` as one of it's private fields.

**Comment by kofi12** [comment]
Great, I've update the wiki with all the justifications now.
