### ISSUE TITLE
Prepare distribution for the Client Team

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#24]
Basically this should boil down to making the JAR file and adding instructions to the README.

**Comment by kofi12** [comment]
If you go to the main page of the repo, on the right hand side you should see "Releases". You can click on that and download the jar from there. On Mac the jar won't open when you click the first time, have to go into security settings and allow the app to be opened. Once that's done it works fine

**Comment by kofi12** [comment]
Try it out and let me know how it works on Linux, also anybody who works on windows @LJWoolner should try it and see if it works

**Comment by kofi12** [comment]
I've updated the [ReadME](https://github.com/Macintosh001/EECS-3311-final-project#readme) with some setup instructions for macOS, perhaps you guys can add instruction for linux and windows
