### ISSUE TITLE
Finish the product update dialog/logic

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#31]

**Comment by kofi12** [comment]
I'm working on the update dialog class as we speak, if someone could work on the logic side `updateProduct()` that would be great.

**Comment by kofi12** [comment]
Question, when we update a product should also be able to update the barcode?

**Comment by glassyeyedfish** [comment]
As far as I can tell, with the new UI/Logic finished, this is done and working.
