### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#33]

**Comment by kofi12** [comment]
What do you guys think about the filter button being a drop down menu with options corresponding to the various fields or something. Also perhaps we should think about what the options should be. Should the filter class be several classes, example. `FilterByPrice` being its own class

**Comment by glassyeyedfish** [comment]
So far, we are just missing the UI for the Date Filters and then we can check this one off.

**Comment by kofi12** [comment]
I'll look into it, this is in the `StockCheckingView` correct?
