### ISSUE TITLE
CouponManagerView input validation

### ISSUE THREAD

**Issue by kofi12** [Macintosh001/EECS-3311-final-project#49]
In the branch [iter2-ui-integration](https://github.com/Macintosh001/EECS-3311-final-project/tree/iter2-ui-integration) run the app. Inputting a coupon triggers input validation when I input a number like 34. It asks for a number between 0 and 100 but still shows an error regardless. Error is perhaps occurring in the percentage input validator

**Comment by glassyeyedfish** [comment]
Found the bug. 

In the class `PercentOffValidator`, line 17 change it from:
`if (0.0f <= result && result <= 100.0f) {`
to
`if (!(0.0f <= result && result <= 100.0f)) {`

Basically it was doing the opposite of what it was supposed to.
