### ISSUE TITLE
StockCheckingView bug

### ISSUE THREAD

**Issue by kofi12** [Macintosh001/EECS-3311-final-project#50]
does not render a screen when running app. Not sure what the issue is at the moment.

`iter2-ui-integration` branch

**Comment by kofi12** [comment]
problem occurs when utilizing date pickers for the date fields. Commented the code out for now until I can fix the issue

**Comment by glassyeyedfish** [comment]
I didn't include the date filter, so this is still technically a problem. I'm gonna make a new issue for it though, so closed for now.
