### ISSUE TITLE
Add back buttons for the views

### ISSUE THREAD

**Issue by kofi12** [Macintosh001/EECS-3311-final-project#54]

**Comment by kofi12** [comment]
I believe all back buttons are functional now except clicking on the "Coupons" button in the Manager View takes you back to the Initial page. I'm sure the bug quite simple to solve but I can't seem to see it. Places to look 

ManagerView class

`JButton couponButton = new JButton("Coupons");
        couponButton.setBounds(200, 10, 200, 50);
        couponButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CouponManagerView cView = new CouponManagerView(scLogic,sLogic,cLogic,smLogic,oLogic);
                frame.dispose();
            }
        });`

Hope someone can catch it

**Comment by kofi12** [comment]
I'll just give the line number lol. Number 39 - 47 in `ManagerView` is where I think the problem is. Perhaps it is somewhere else though.

**Comment by glassyeyedfish** [comment]
The new stack based JPanel system solves this problem.
