### ISSUE TITLE
Add Date Filter UI elements to StockCheckingView and StockManagingView

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#62]
Right now we can filter by Price and Quantity, but that's it.

**Comment by kofi12** [comment]
I've added date pickers to simplify the date filter process. They are working, I couldn't test it out in the working-main branch however so I tested it in the more-unit-testing branch which utilizes the stubs.

**Comment by glassyeyedfish** [comment]
Tested these using the real SQL DB, they seem to work. Closed! Thanks Aaron!
