### ISSUE TITLE
BUG: In SaleLogic/SaleView, it never reports an error when you scan too much

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#65]
Let's say there are 3 apples in stock with barcode 4. When I scan barcode 4 more than 3 times it doesn't report an error, it just lets me add 4 apples to the cart. After that, when I buy them nothing is removed from stock at all.

**Comment by wqs1997017** [comment]
The buy() function has a logic that will judge the quantity between the cart and the inventory. It's like when the quantity of the inventory is less than the cart, then will have an error message that shows "Product out of stock".

**Comment by glassyeyedfish** [comment]
Fair enough. I'll go make the fix in the UI.

**Comment by glassyeyedfish** [comment]
Fixed.
