### ISSUE TITLE
Date filters in manage stock view

### ISSUE THREAD

**Issue by LJWoolner** [Macintosh001/EECS-3311-final-project#77]
Date filters are working in the employee stock view, but not at all in the manage stock view.

**Comment by LJWoolner** [comment]
Even when using the stub rather than the real database, the date filters do not work in the manager stock view.

**Comment by kofi12** [comment]
Fixed bug. Was missing a line in the confirmButton action listener `datePicker.getDateStringOrEmptyString(), datePickerMax.getDateStringOrEmptyString()`
