### ISSUE TITLE
Quantity setting problem

### ISSUE THREAD

**Issue by Winfred01** [Macintosh001/EECS-3311-final-project#83]
There is a problem with the inconsistent display when entering large numbers.
![6e7e2b01d9e815d6dec35a88021e748](https://user-images.githubusercontent.com/91762181/225811685-5df84dc4-c159-44e5-a34b-c25db2e579cf.png)
![f7e3eb7d59e23a300cf787d358b1b1a](https://user-images.githubusercontent.com/91762181/225811697-57c712e2-d44c-4042-b922-d4cf882f3cc4.png)

**Comment by glassyeyedfish** [comment]
Set the max price to $100'000 to fix this issue.
