### ISSUE TITLE
There is no hint of an upper limit when setting Quantity

### ISSUE THREAD

**Issue by Winfred01** [Macintosh001/EECS-3311-final-project#84]
When users type large ints, they get the wrong feedback.
![cee41d85378342621cc85b48f48ab3c](https://user-images.githubusercontent.com/91762181/225812094-06a85ae4-9cfc-42e3-8691-3d8d270071a1.png)

**Comment by LJWoolner** [comment]
QA team suggested this issue. 
Fix: added some error messages if the integer entered is too large. This change took place in our QuantityValidator class.

**Comment by LJWoolner** [comment]
More detail: after a NumberFormatException is thrown, try to create a BigInteger object from the input. If successful, compare the big integer to the max value of integers. If too large, create an error message that says so.
