### ISSUE TITLE
Customer use coupon problem

### ISSUE THREAD

**Issue by Winfred01** [Macintosh001/EECS-3311-final-project#85]
After a user has used a coupon once, the last discount code will be automatically used for future purchases and no new coupons can be used.
![fa2c28321cd86aa4cc8c9a290604e8e](https://user-images.githubusercontent.com/91762181/225812443-d3d87c83-6076-4195-a2d8-7c13144b93d5.png)

**Comment by glassyeyedfish** [comment]
I applied Jeremy's fix, but haven't testes it yet

**Comment by glassyeyedfish** [comment]
Check it now, looks like it's working.

**Comment by glassyeyedfish** [comment]
Bugfix: Added code to reset the coupon inside of the `clearShoppingCart()` function.
