### ISSUE TITLE
User interface fractional digit display problem

### ISSUE THREAD

**Issue by Winfred01** [Macintosh001/EECS-3311-final-project#86]
Display of too many decimal places in the user interface is not necessary
![ac39acb91ced28d3fc6206913301fd7](https://user-images.githubusercontent.com/91762181/225812656-f64c4625-1a2b-410b-876d-60246a3e813a.png)

**Comment by glassyeyedfish** [comment]
Fixed.

**Comment by glassyeyedfish** [comment]
Changed `TableEntryGenerator` to truncate the floating point numebr.
