### ISSUE TITLE
Removing modifier bug in ModifierManagerView

### ISSUE THREAD

**Issue by kofi12** [Macintosh001/EECS-3311-final-project#98]
When I click remove and enter the name "sale2", it doesn't not remove the entry but displays the error message instead. Perhaps I'm missing something.

`ui-refinement` branch `ModifierManagerView`. Look around line 63.

**Comment by glassyeyedfish** [comment]
What error message does it display?

**Comment by kofi12** [comment]
says there is no "sale2" to remove

**Comment by kofi12** [comment]
bug is fixed. Thanks @glassyeyedfish .
